### ISSUE TITLE
rapidgator issue

### ISSUE THREAD

**Issue by ducd** [mcrapet/plowshare#105]
I tried to download from rapidgator and got these errors

>parse_all failed (sed): "/^[Cc]ontent-[Dd]isposition:/ s/^.*filename\*\?=["']\?\([^"'[:cntrl:]]*\).*$/\1/p" (skip 0)
>Failed inside grep_http_header_content_disposition(), line 837, core.sh
>Failed inside rapidgator_download(), line 318, rapidgator.sh
>Failed inside rapidgator_download() [1]

**Comment by mcrapet** [comment]
Hi,

1. Please submit this issue in [plowshare-modules-legacy repository](https://github.com/mcrapet/plowshare-modules-legacy/issues/). This is the core repository, and the issue is from a module.

2. When you do, please format the code following [Github's guide to Markdown.](https://guides.github.com/features/mastering-markdown/)
