### ISSUE TITLE
$PREFIX/share/plowshare/modules.d/ is not supported?

### ISSUE THREAD

**Issue by zeule** [mcrapet/plowshare#2]
Hello!

I'm the reporter of [issue 1271](https://code.google.com/p/plowshare/issues/detail?id=1271) on Google Code.

I don't want to update plowshare modules manually, but instead my package manager (well, a helper program) updates them when it detects changes in the repositories.

So, I've installed them into $PREFIX/share/plowshare/modules.d/. I do have two subdirs there: legacy and mega. But `plowdown` reports:
    $ plowdown 
    -------------------------------------------------------------------------------
    Your plowshare installation has currently no module.
    (/home/eugene/.config/plowshare/modules.d/ is empty)

If I symlink $PREFIX/share/plowshare/modules.d/ into ~/.config/plowshare/ it finds modules. However, in the [original bug discussion](https://code.google.com/p/plowshare/issues/detail?id=1271) I was told that $PREFIX/share/plowshare/modules.d/ is supported.

**Comment by mcrapet** [comment]
Hi,

As written in the googlecode issue:

`$PREFIX/share/plowshare/modules/` is supported "for historical reasons" but not `$PREFIX/share/plowshare/modules.d/`.

Do consider using `plowmod` it's made to be simple to update modules sources (using git).

PS: mega repository is actually not a good example because it must installed, it can't work "in place" like modules-legacy.

**Comment by zeule** [comment]
I see. It seems to me that I better leave `$PREFIX/share/plowshare/modules.d/` -> `$HOME/.config/plowshare/modules.d` symlink. I already have the software that updates software, and it is my package manager. Why do I want to use a second one?

Thank you for the clarification though.
