### ISSUE TITLE
existing cookie file support for plowup

### ISSUE THREAD

**Issue by Konstantinusz** [mcrapet/plowshare#21]
I read in the manual that plowdown supports to define an already existing cookie file with option --cookies. I wanted to tried this out with plowup, because I extracted my cookies from Chromium into a text files. Would be convenient to use them with plowup, for example when uploading to depositfiles.com / dfiles.eu because that site sometimes asks for a captcha, but when I type the text from imgur it doesn't recognize it, and it is an annoyance. I simply would use my existing cookie file when uploading.

**Comment by mcrapet** [comment]
Hi,

--cookies is a very old option and has been discarded a long time ago.
It has been replaced by --cache. See documentation about **--cache** in manpages.

plowup depositfiles support account upload but do not support cache mecanism.

So your only solution is to use:
`$ plowup -a 'user:password' file1.rar file2.rar file3.rar`

As this request concerns a module and not plowshare core, next time, please open your issue here:
https://github.com/mcrapet/plowshare-modules-legacy/issues

Thanks!

**Comment by mcrapet** [comment]
https://github.com/mcrapet/plowshare-modules-legacy/issues/14
