### ISSUE TITLE
Upload speed | Seedbox

### ISSUE THREAD

**Issue by hchaucha** [mcrapet/plowshare#38]
Hey,
I put Plowshare on my seedbox, it's seem to work correctly but the upload speed is very low. I should be able to enjoy of the high spped of my seedbox, right ?

**Comment by Raziel-23** [comment]
Please test your download and upload speed on your seedbox with this command:

`curl -s https://raw.githubusercontent.com/blackdotsh/curl-speedtest/master/speedtest.sh -o- | sed -e '/America/,/Paris/s/^/#/;/Alblasserdam/,$s/^/#/;$aunlink \$fileName\;' | bash`

Note: This script is taken from [here](https://github.com/blackdotsh/curl-speedtest). I used sed to comment out other servers except Paris. Depending on your geographical location you can download this script and choose/comment out other servers to test.

I highly doubt that this issue is related to plowshare, unless you limit your upload speed with --max-rate option. Most probably this issue is related to your seedbox and service where you upload. Less probably it may be related to curl version you are using on your seedbox, maybe older version with bugs.

**Comment by hchaucha** [comment]
Thanks to your quick reply. 
I tested the following command line and I have a good seed upload (15 mb/s).
I don't think that I block my speed with anything.
It's weird. I will going to send a ticket to my seedbox

**Comment by mcrapet** [comment]
`curl -s dl.getipaddr.net/speedtest.EU.sh -o- | bash`
