### ISSUE TITLE
Save uploaded links in log file?

### ISSUE THREAD

**Issue by greenzwiz** [mcrapet/plowshare#45]
Is it possible to save the uploaded files links and filename to a log file? Is this feature available? I searched and can't seem to find it in the docs. 
Thanks!

Example log file:

```
myfile.zip - - 2016-04-20 14:20:00 - - zippyshare  - -  http://www77.zippyshare.com/v/78jhYis/file.html
anotherfile.zip - - 2016-04-20 14:20:00 - - depositfiles  - -  http://depositfilescom/v/78jghdd
```

**Comment by mcrapet** [comment]
Hi,

Something like `plowup --printf='%f - - <date> - - %m - - %u'` should do the job. Just redirect command (stdout) to a file.

**Comment by mcrapet** [comment]
Time is now available for `--printf` of plowup: see https://github.com/mcrapet/plowshare/commit/f28c2e6dcbd6552b1808119c126190556efddb42.

Your command line could now be something like: `MYDATE='2016-XX-XX' plowup --printf="%f - - $MYDATE %T - - %m - - %u"` (shell is replacing MYDATE variable because we double quoted)
