### ISSUE TITLE
incrontab 

### ISSUE THREAD

**Issue by Erkalos** [mcrapet/plowshare#48]
I use plowup in shell script :
`link_uptobox=$(sudo /usr/bin/plowup  uptobox $1 | grep -v "#")
`
When i start manually it work but if use Incron to start the script it does not work, no upload and no return of link.
Incrontab -e :
`/home/dl/fichiers IN_CREATE sh /home/dl/upload.sh $@/$#
`
If i use "logger" i can watch in my log :
`logger: /usr/bin/plowup -q uptobox /home/dl/fichiers/test2.mkv | grep -v "#"
`
Do you have an idea ? 

Os : centos 7

**Comment by mcrapet** [comment]
Hi,

I guess that it us an environment issue. Is `$HOME` defined ?

**Comment by Erkalos** [comment]
what do u mean ?  i don't exactly understand. I need to specify $home in my script ?

**Comment by mcrapet** [comment]
plowdown uses `$HOME` to locate `~/.config/plowshare/plowshare.conf` (if existing) and modules (`~/.config/plowshare/mdoules.d/`). Session cookies could also be saved in `~/.config/plowshare/storage/`).

Since a year (or more) modules are not anymore systemwide but related to a user. However it is still possible to have the systemwide behavior (`/usr/share/plowshare/modules/` is considered).

I'll add a check for `HOME` existence.

You should do something like this in your script.

<pre>
export HOME=/home/xxx
logger -- /usr/bin/plowup uptobox -q --printf '%u%n' /home/dl/fichiers/test2.mkv
</pre>

You can add also a custom tmpdir if you want: `--temp-directory=/mytmp`.

**Comment by Erkalos** [comment]
still does not work, i'm desperate :(
I paste my script : http://0bin.net/paste/DF-N8WoYdFstphnz#33ByIJt+cM6Y6+toqd4dmClC-I15arel/q2cW+A0VJF
Like I say before it work when I start it manually but not when it start with incron :$

**Comment by mcrapet** [comment]
Where are your modules ?

drop `-q` and redirect stderr to stdout to have more information.

`plowup -v3 --no-color   ...   2>&1`

**Comment by Erkalos** [comment]
It WORK ! :D
Thanks :), i just change plowup -q with plowup -v3 --no-color and it work fine :D 
`logger: INSERT INTO test (date,nom,link_uptobox,link_jheberg,type,size) VALUES ("20160518","test10.mkv","http://uptobox.com/******","http://jheberg.net/download/******/","mkv","264M");`
