### ISSUE TITLE
Forced wait even if premium user

### ISSUE THREAD

**Issue by ghost** [mcrapet/plowshare#51]
When i download my files via textfile and as a premium account user, plowdown always forces a 30-secound wait inbetween links. 
Output says : "Same previous hoster, forced wait requested"
Is there a reason to it, or is it a bug?

Thanks!

**Comment by Raziel-23** [comment]
In a particular module must be set for all users the following global variable:

```
MODULE_XXX_DOWNLOAD_SUCCESSIVE_INTERVAL=30
```

You have to give me a service name, then I will change it for premium accounts.

**Comment by Raziel-23** [comment]
Nevermind, only `uploaded_net` module has such global variable, see [here](https://github.com/mcrapet/plowshare-modules-legacy/blob/master/uploaded_net.sh#L307). You can change it and test how it works for you, because it is set there for a reason. Maybe it is not needed anymore and can be set to 0, but I don't have a premium account there so you have to test it.

**Comment by ghost** [comment]
I'll give a try tommorow and report back. Thanks !

Edit : Just edited the constant from 30 to 0 and everything works as usual. No errors or slow download performance.

**Comment by mcrapet** [comment]
Unless exeption, `MODULE_xxx_DOWNLOAD_SUCCESSIVE_INTERVAL` must be set 0 when using premium account. See `bayfiles.sh` for an example.

**Comment by Raziel-23** [comment]
@mcrapet So we leave it there as it is, or we change it to 0? I prefer to ask, because I'm not the author of this module and maybe setting this there is still valid.

**Comment by mcrapet** [comment]
@jedipimpmasterflex Next time, open issue on plowshare-modules-legacy. Thanks.

https://github.com/mcrapet/plowshare-modules-legacy/commit/ad891aacb4ae40a87edfc12b012de3f4b6ce1204
