### ISSUE TITLE
Plowmod is not working?

### ISSUE THREAD

**Issue by 5kon** [mcrapet/plowshare#76]
Hello,

I've installed plowshare on my VPS (OS: debian-8.0-x86_64). When I install external modules using `plowmod --install`, it shows `-bash: plowmod: command not found`. 

I'm new to Bash and have no idea why there is no `plowmod` command. Does anyone know the reason? Any help is really appreciated.

**Comment by mcrapet** [comment]
Hi,
Which version of plowshare did you installed ?
Could you list your installation directory (for example when prefix=`/usr`):
`$ ls /usr/share/plowshare/`

**Comment by arcresu** [comment]
Since your VPS is running Debian jessie, if you installed plowshare from the software repository as the package `plowshare4` then you are stuck with using an old version (1.0.5) pre-dating `plowmod`. To get the latest versions you should [enable jessie backports](https://backports.debian.org/Instructions/) and then perform an update which will replace the `plowshare4` package with `plowshare` at version 2.1.5 (soon to be 2.1.6 once I get that uploaded in the backports repository). These newer versions will have `plowmod` included,

**Comment by 5kon** [comment]
I've checked `ls /usr/share` and found `plowshare4`. Then I check `ls /usr/share/plowshare4` ,it shows `core.sh  delete.sh  download.sh  list.sh  modules  probe.sh  upload.sh`. Is this an outdated version?

**Comment by arcresu** [comment]
Yes, you have the old version from jessie without `plowmod`. The new version is in a package called `plowshare` (without the 4) which is available in jessie backports.

**Comment by 5kon** [comment]
@arcresu Thanks! `plowmod` works after updating the package.

Besides, I find the `plowshare` package in the CentOS 7 is also outdated. The package version is 1.0.6 and there is no `plowmod` function. @mcrapet 

Thanks for both of your help.
