### ISSUE TITLE
plowdown zippyshare

### ISSUE THREAD

**Issue by christ84** [mcrapet/plowshare#79]
Hi, I can't upload a file on zippyshare.com but I can't download a file from this hoster (module is missing), how I can fix that? Thx

**Comment by mcrapet** [comment]
Greeting,

This issue belongs ot [plowshare-modules-legacy repository](https://github.com/mcrapet/plowshare-modules-legacy/issues/).
This is the core repository, and the issue is from a module.

Please do read [CONTRIBUTING.md](https://github.com/mcrapet/plowshare-modules-legacy/blob/master/CONTRIBUTING.md).

Thanks.
